---
title: "Análise do efeito da mudança na cota-parte do ICMS na Saúde"
author: 
  - Tony Araujo
  - Walacy Oliveira
  - Brysa
  - Diego Carneiro
  - Felipe
  - Guilherme Irffi
  - Pedro Veloso
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
    html_document:
       highlight: textmate
       theme: flatly
       number_sections: yes
       toc: yes
       toc_float:
         collapsed: yes
         smooth_scroll: no
#knit: pagedown::chrome_print
params:
  ano_lei:
    label: "Ano que a Lei foi implementada"
    value: "2007"
    input: slider
    min: 1996
    max: 2019
    step: 1
    sep: ""
  uf_tratado:
    label: "Estado tratado"
    value: "CE"
    input: select
    choices: [AP, CE, MG, ES, RS, MT]


---
**Estado analisado:** `r params$uf_tratado`

**Ano Internvenção:** `r params$ano_lei`

**Varíavel de resultado:** 


```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
```

```{r pacotes, results='hide', echo=FALSE}
#Pacotes que serão utilizados 
pacotes = c("tidyr","tidylog", "tidyverse", "janitor","DataExplorer", "flextable", "psych", "scales",
            "kableExtra")

lapply(pacotes, require, character.only = T)

rm(pacotes, x)

```

```{r dados, results='hide', echo=FALSE}
#importar dados 
load("../processed-data/base_dados_geral.Rda")
dados <- dados %>% mutate(id_municipio = as.numeric(id_municipio)) #modificar variavel id municipio para numerica

```


```{r gerar_regiao, results='hide'}
dados <- dados %>% 
  mutate( regiao = case_when( between( id_municipio_6, 100000, 199999) ~ "N",
                            between( id_municipio_6, 200000, 299999) ~ "NE",
                            between( id_municipio_6, 300000, 399999) ~ "SE",
                            between( id_municipio_6, 400000, 499999) ~ "S",
                            between( id_municipio_6, 500000, 599999) ~ "CO"))

```


```{r menus_tratados_controles, results='hide'}
#Filtrar municipios de acordo com o tratado

base_analise <- dados %>% 
    filter(case_when( params$uf_tratado == "AP" ~ regiao == "N",
                           params$uf_tratado == "CE" | 
                           params$uf_tratado == "PE"  ~ regiao == "NE",
                           params$uf_tratado == "MG" |
                           params$uf_tratado == "ES" ~ regiao == "SE",
                           params$uf_tratado == "RS" ~ regiao == "S",
                           params$uf_tratado == "MT"  ~ regiao == "CO"))

```

```{r menu_dif_dif, results='hide'}
base_analise <- base_analise %>% 
  mutate(tratado = case_when(sigla_uf == params$uf_tratado ~ 1, TRUE ~ 0), #tratado é 1 e demais são zero.
         ano_tratamento = case_when(between (ano, params$ano_lei, 2019) ~ 1, #após ano implementação é periodo de tratamento, caso contrario é zero
                                    TRUE ~ 0))
```

```{r excecoes, results='hide'}
ifelse(params$uf_tratado == "CE", #se tratado for CE
       base_analise <- base_analise %>% 
         filter(sigla_uf != "PE"), #excluir PE
       ifelse(params$uf_tratado == "MG", #se tratado for MG
              base_analise <- base_analise %>% 
                filter(sigla_uf != "ES"), #excluir ES
              ifelse(params$uf_tratado == "ES", #se tratado for ES
                     base_analise <- base_analise %>% 
                       filter(sigla_uf != "MG"), #escluir MG
                     base_analise
              )))




```


```{r parametros, results='hide'}
#Numero de medicos por 1000 habitantes
base_analise <- base_analise %>% 
  mutate(medicos_1k_hab_esf = (n_medicos_esf/pop_res)*1000)

#Gasto em saúde e saneamento, deflacionado,  percapita.
base_analise <- base_analise %>% 
  mutate(gasto_saude_per = health2 / pop_res)


# variaveis de resposta da politica
var_r = c("tmi1", "tmi5", "medicos_1k_hab_esf" )

```



# Pré análise usando dados não pareados

## Diferença nas médias: Variável de resultado

```{r, echo=FALSE}

base_analise %>%
  group_by(tratado) %>%
  summarise(
    across(
      var_r,
      .fns = list(
        "N.Obs" = ~ n(),
        "Média" = ~ mean(.x, na.rm = T),
        "Mediana" = ~ median(.x, na.rm = T),
        "Mín" = ~ min(.x, na.rm = T),
        "Máx" = ~ max(.x, na.rm = T),
        "Desvio-Padrão" = ~ sd(.x, na.rm = T)
      ),
      #.names = "{.fn}"
    ),
    .groups = "drop"
  ) %>% 
  kable(digits = 3, booktabs = T) %>% 
  add_header_above(c("Grupo" = 1, "TMI 1" = 6, "TMI 5" = 6, "Médicos ESF por mil hab. " = 6))
  

```











